### ISSUE TITLE
How to generate trigger by myself for the lf attack?

### ISSUE THREAD

**Issue by mo666666** [SCLBD/BackdoorBench#10]
Hi, SCLBD! Thank you for your excellent work! I have a question for the low-frequency attack: How to generate the trigger by myself for the model of a new architecture?

**Comment by April4lu** [comment]
You can refer to the link [https://github.com/YiZeng623/frequency-backdoor/tree/main/Sec5_Smooth_Trigger](url). It might be helpful!

**Comment by mo666666** [comment]
Thank you for your reply. As I know, the [repository](https://github.com/YiZeng623/frequency-backdoor/blob/main/Sec5_Smooth_Trigger/target_universal.py) only provides the Tensorflow version code for lf attack and can only generate the trigger of the Inception model. Therefore, I would like to ask: what adaptation do I need to make to transfer it to other architectures? In addition, can the trigger which is generated by this [repository](https://github.com/YiZeng623/frequency-backdoor/blob/main/Sec5_Smooth_Trigger/target_universal.py) be directly applied to the BackdoorBench?

**Comment by April4lu** [comment]
The code of low-frequency trigger generation will be released this week.

**Comment by mo666666** [comment]
Thank you for your kindness! Look forward to the release of the relevant codes！

**Comment by mo666666** [comment]
Hi, April4lu. Can't wait to see the code of low-frequency trigger generation. Do you plan to release the relevant code this week?

**Comment by CHR-ray** [comment]
You can find generation code at https://github.com/SCLBD/BackdoorBench/tree/main/resource/lowFrequency

**Comment by mo666666** [comment]
Ok, thank you very much!
