### ISSUE TITLE
concern about backdoor_generate_pindex.py

### ISSUE THREAD

**Issue by huangd1999** [SCLBD/BackdoorBench#13]
First, think about this benchmark, which helps me to reproduce baseline experiment results quickly. However, I have a few concerns about the code in the backdoor_generate_pindex.py. Specifically, we can see that in https://github.com/SCLBD/BackdoorBench/blob/main/utils/backdoor_generate_pindex.py#L59,

```
non_zero_array = np.random.choice(np.where(targets == tlabel)[0], round(pratio * len(targets)), replace = False)
```
 
Seems like the non_zero_array is selected from the label, maybe there should use targets!=tlabels.

**Comment by CHR-ray** [comment]
Hi huangd1999, 

Please notice that before you reach this line, you should first meet the condition in the  if-statement for clean-label. So by the definition of clean-label attack, we can only use poison samples from target class, I think this line is correct.

If you have any further question, feel free to ask.

**Comment by huangd1999** [comment]
Thanks for your response, after checking the code, I found that clean_label = True is only used in lc_attack and sig_attack, which is consistent with the paper.

(: Very thanks for this benchmark.
