### ISSUE TITLE
Bugs in WaNet All2All Attack

### ISSUE THREAD

**Issue by huyvnphan** [SCLBD/BackdoorBench#18]
Hi,

I think in the WaNet Attack All2All attack case, the code to calculate targets_bd is wrong.

https://github.com/SCLBD/BackdoorBench/blob/408db06c39e404cc720043afdc07285613dc322a/attack/wanet.py#L301-L302

Reference code from WaNet's GitHub.

```
if opt.attack_mode == "all2all":
    targets_bd = torch.remainder(targets[:num_bd] + 1, opt.num_classes)
```

https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release/blob/94453080f241053ac7c8cc4717da20806ee17e5c/train.py#L82-L83

**Comment by CHR-ray** [comment]
You are right, I updated that part in recent commit [4eb9c8b](https://github.com/SCLBD/BackdoorBench/commit/4eb9c8b1a9b29af3e1ce95a3beac5ab533a0d7b4). 
If you have any further comment, please let me know.
