### ISSUE TITLE
the data of leaderboard(asr of blended to nad)

### ISSUE THREAD

**Issue by coldpark** [SCLBD/BackdoorBench#19]
Thank you for sharing your work with the community and for all that you do. Your project has made a difference in the lives of many people, and for that, I am truly grateful.
However, I have some concerns regarding the accuracy of the results displayed on the leaderboard. Specifically, I noticed that the success rate of the traditional attack method blended against defense methods such as nad/nc appears to be too high. After attempting to replicate the nad defense against blended attacks, I found that the results were not as good as those reported in the original paper but also not as bad as those presented on the leaderboard.
Can you review the accuracy of the results on the leaderboard to ensure they are reflective of the true performance of the defense methods?
Thank you for your attention to this matter.

**Comment by mdzhangst** [comment]
Well, there is a possible reason. The blended attack uses a relatively high degree of blending. This makes many defense methods fail. Thank you very much for your experiment. We will also review the specific results later.
