### ISSUE TITLE
LC attack source

### ISSUE THREAD

**Issue by yyang318** [SCLBD/BackdoorBench#26]
Very nice work. May I confirm that the LC attack is [Label-Consistent Backdoor Attacks](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjvwKTx2bH4AhXCD0QIHVMWApkQFnoECAsQAQ&url=https%3A%2F%2Farxiv.org%2Fabs%2F1912.02771&usg=AOvVaw0NbPR9lguGTsEn3ZWtPBDR) as shown in this project. In the paper, the LC attack cites the paper [Poison Frogs! Targeted Clean-Label Poisoning Attacks on Neural Networks](https://arxiv.org/abs/1804.00792).

**Comment by CHR-ray** [comment]
Yes, that's a typo. Sorry to confuse you. LC is for Label-Consistent Backdoor Attacks, not poison frogs.
You can refer to resource/label-consistent and utils/bd_img_transform/lc.py for more information.
