### ISSUE TITLE
can not generate trigger for low frequency attack

### ISSUE THREAD

**Issue by a-cup-of-joe** [SCLBD/BackdoorBench#29]
Thank you for sharing your work! It's really helpful.
However (excuse me), I can't generate trigger for low frequency attack with resources/lowFrequency/generate_pattern.py.
There's no errors in execution, but the fooling rate in Universal Perturbation algorithm keeps 0 in 50 epochs （it just doesn't change）, which means the perturbation is not optimized and the agorithm is not working.
The picture below shows the fooling rate in epoch 12.
<img width="514" alt="image" src="https://github.com/SCLBD/BackdoorBench/assets/58138391/3083fa76-147c-4e9d-a7a3-5e77cce92463">
Here's some information:
- I've already installed the packages in requirement.txt file
- I tried to generate trigger on cifar10 dataset, with several clean models you provided in Google drive, but none of them works.
- I used default.yaml and cifar10.yaml (in resources/lowFrequency) to test, only edit necessary parameters(model path or type, for example), left most parameter unchanged.
- I've removed "{iter}" in code below, for it brings errors in execution. The code is about saving the trigger image and I guess this won't influence the algorithnm. I didn't make other change except this.
https://github.com/SCLBD/BackdoorBench/blob/04137b76a2f8ec771444823ddbc6d6bd57e27214/resource/lowFrequency/generate_pattern.py#L268-L272

Your work is the only pytorch-based implementation for lf attack that I can find. The triggers you provided is useful and I'm grateful, but I still want to generate my own triggers. 
I want to ask how can I solve this problem. Thanks in advance!

**Comment by CHR-ray** [comment]
The code of this perturbation generation is from the paper we replicate and we did not change that part. 
The fooling rate does not influence the training process of backdoor model much.  What we observed is that even if the fooling rate is low, the attack process can still be successful. I remember when we run the script it is also low, but we found that the perturbation actually works in the attack process. And you can observe that the perturbation itself looks like adding a filter to images by your eyes. Hopes this information can help you. I suggest you to run the attack with perturbation you get first.

**Comment by a-cup-of-joe** [comment]
Thanks for your answer. It really solves my confusion. Thanks again for your great work!
