### ISSUE TITLE
A resource of `lc_atyack` is missing

### ISSUE THREAD

**Issue by SheltonLiu-N** [SCLBD/BackdoorBench#3]
Hi, 
It seems that a resource of `lc_atyack` is missing:
`FileNotFoundError: [Errno 2] No such file or directory: '../resource/label-consistent/data/adv_dataset/cifar10_train.npy`
Did I forget to download it?
Thanks!

**Comment by CHR-ray** [comment]
Sorry to reply late... The link to lc attack file in is https://drive.google.com/drive/folders/1Qhj5vXX7kX74IWdrQDwguWsV8UvJmzF4?usp=sharing
