### ISSUE TITLE
How can i use the Vit model.pt ?

### ISSUE THREAD

**Issue by 2022wannarest** [SCLBD/BackdoorBench#41]
Hello, thank you for the thorough summary you provided.

I encountered some problems. I imported it in torch-vision.model— and conducted color backdoor attack experiments. Therefore, I wanted to evaluate the defense after the attack, but I found that the contents of my weight file differed from those of Git Hub. The format of attack_result.pt is different, so it cannot be defended directly. 
For example, the following problem report.

![image](https://github.com/SCLBD/BackdoorBench/assets/102201152/0e2b0bad-5de8-4117-a197-133d92851259)

![image](https://github.com/SCLBD/BackdoorBench/assets/102201152/cbd657c4-a5bf-46af-b6d2-cf2ddda5c40f)
 
How can I solve the problem? Thanks

**Comment by CHR-ray** [comment]
Sorry to reply late. 
Please follow the [save_load_attack.py](https://github.com/SCLBD/BackdoorBench/blob/main/utils/save_load_attack.py) **strictly**, this function shows how to save a result that defense can use.
