### ISSUE TITLE
can not generate trigger using low frequency attack for resnet18

### ISSUE THREAD

**Issue by zyq726** [SCLBD/BackdoorBench#42]
python generate_pattern.py --dataset cifar10 --model resnet18 --clean_model_path ../../resource/clean_model/cifar10_resnet18/clean_model.pth --save_folder_name lf
When I use this python code，it will response the error ModuleNotFoundError: No module named 'resnet18'
![1715343152331](https://github.com/SCLBD/BackdoorBench/assets/76116993/2fa35140-5715-46ea-b896-80863c1c7f9a)

**Comment by CHR-ray** [comment]
You need to add resnet18 to this script by yourself, we initially only support those models used in our paper. But I believe it will not be hard, and only require several lines of codes.
