### ISSUE TITLE
Model Zoo and Onedrive link cannot be accessed

### ISSUE THREAD

**Issue by EnnengYang** [SCLBD/BackdoorBench#46]
Dear authors,

Thank you very much for providing the complete attack and defense baselines, it is a great work.

You mentioned in README.md: We recommend you to download the data and model from [model zoo](http://backdoorbench.com/model_zoo) of our website ,  but we also provide the whole onedrive link at [Backdoor Model](https://cuhko365-my.sharepoint.com/:f:/g/personal/backdoorbench_cuhk_edu_cn/EimE1JoHs4ZAivBThQeLkocBs5uPmj20JEtnEIBkJhS0tw?e=gtsc9z) as an alternative source for your convenience.

However, I tried both links and they didn't work. model zoo has been unresponsive and Onedrive cannot be opened.

Therefore, I would like to ask you to **update the latest accessible links**.

Looking forward to your reply.

Thanks.

**Comment by mdzhangst** [comment]
Thank you very much for your question. I tested the SharePoint link for the Backdoor Model and it was open and downloadable. Due to the unique naming conventions of SharePoint, the model zoo download will be temporarily removed.

**Comment by mdzhangst** [comment]
Sorry, the link to Backdoor Model in readme was updated in the previous update log, but not in the following section. The link has now been updated in both sections.
