### ISSUE TITLE
Missing file when running attack/lc.py

### ISSUE THREAD

**Issue by zjlnbb** [SCLBD/BackdoorBench#53]
![屏幕截图 2024-11-12 233437](https://github.com/user-attachments/assets/c1458611-4079-4dbd-baf0-b856cbb3e41b)

why this error occurs? there is not such file indeed.  Is there any error?

PS: "big" is my filename

**Comment by CHR-ray** [comment]
We mention it in readme. Since this attack need to do PGD first, but we do not want everytime to do PGD again, we save the file first in resource, you can find the line like below:
![image](https://github.com/user-attachments/assets/f54b5988-91dd-4962-8816-61f656b24d19)
