### ISSUE TITLE
Results for CLP - Channel Lipschitzness based Pruning

### ISSUE THREAD

**Issue by huyvnphan** [SCLBD/BackdoorBench#8]
I see this repo has just added a new defense method CLP - Channel Lipschitzness-based Pruning.

Can you update the Leaderboard to include the results of the CLP and README file to update your API?

Thank you for such comprehensive work.

**Comment by mdzhangst** [comment]
In April, we'll update the result of the CLP method and some new methods. We will also update a new unified framework soon, with new methods and some visualizations of the results.
