### ISSUE TITLE
How should we run a label-consistent attack?

### ISSUE THREAD

**Issue by XaiverYuan** [SCLBD/BackdoorBench#9]
My command is `python ./attack/lc_attack.py --yaml_path ../config/attack/lc/cifar10.yaml --dataset cifar10 --dataset_path --save_folder_name xxx --model resnet18`
and the result here is 
![image](https://user-images.githubusercontent.com/40052821/216824645-75a1d9ce-affc-41ce-b4d1-efa0da0d9804.png)

And I checked your git, it does not has that file either... So how should we train the LC attack?

Thank you!

**Comment by kshitijsachan** [comment]
any update on this? I would also like to run this attack

**Comment by CHR-ray** [comment]
Sorry to response late. You can find it either in the google drive link that we put in the readme, or generate by yourself with code in resource folder (https://github.com/SCLBD/BackdoorBench/tree/main/resource/label-consistent).
